#!/bin/sh

ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/2020\ Super\ Baseball\ \(set\ 2\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/2020\ Super\ Baseball\ \(set\ 3\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/2020\ Super\ Baseball\ \(set\ 1\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/3\ Count\ Bout\ _\ Fire\ Suplex\ \(NGM\-043\ _\ NGH\-043\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Alpha\ Mission\ II\ _\ ASO\ II\ \-\ Last\ Guardian\ \(prototype\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Alpha\ Mission\ II\ _\ ASO\ II\ \-\ Last\ Guardian\ \(NGM\-007\ _\ NGH\-007\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Andro\ Dunos\ \(NGM\-049\ _\ NGH\-049\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Aggressors\ of\ Dark\ Kombat\ _\ Tsuukai\ GANGAN\ Koushinkyoku\ \(ADM\-008\ _\ ADH\-008\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Art\ of\ Fighting\ 2\ _\ Ryuuko\ no\ Ken\ 2\ \(NGH\-056\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Art\ of\ Fighting\ 2\ _\ Ryuuko\ no\ Ken\ 2\ \(NGM\-056\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Art\ of\ Fighting\ 3\ \-\ The\ Path\ of\ the\ Warrior\ \(Korean\ release\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Art\ of\ Fighting\ 3\ \-\ The\ Path\ of\ the\ Warrior\ _\ Art\ of\ Fighting\ \-\ Ryuuko\ no\ Ken\ Gaiden.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Art\ of\ Fighting\ _\ Ryuuko\ no\ Ken\ \(NGM\-044\ _\ NGH\-044\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Bang\ Bang\ Busters\ \(2010\ NCI\ release\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Bakatonosama\ Mahjong\ Manyuuki\ \(MOM\-002\ _\ MOH\-002\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Bang\ Bead.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Blue\'s\ Journey\ _\ Raguy\ \(ALM\-001\ _\ ALH\-001\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Blazing\ Star.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Breakers.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Breakers\ Revenge.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Baseball\ Stars\ 2.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Baseball\ Stars\ Professional\ \(NGH\-002\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Baseball\ Stars\ Professional\ \(NGM\-002\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Burning\ Fight\ \(NGH\-018_\ US\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Burning\ Fight\ \(prototype\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Burning\ Fight\ \(NGM\-018\ _\ NGH\-018\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Crossed\ Swords\ \(ALM\-002\ _\ ALH\-002\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Crouching\ Tiger\ Hidden\ Dragon\ 2003\ Super\ Plus\ alternate\ \(The\ King\ of\ Fighters\ 2001\ bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Crouching\ Tiger\ Hidden\ Dragon\ 2003\ Super\ Plus\ \(The\ King\ of\ Fighters\ 2001\ bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Crouching\ Tiger\ Hidden\ Dragon\ 2003\ \(The\ King\ of\ Fighters\ 2001\ bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Captain\ Tomaday.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Cyber\-Lip\ \(NGM\-010\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Digger\ Man\ \(prototype\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Double\ Dragon\ \(Neo\-Geo\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Eight\ Man\ \(NGM\-025\ _\ NGH\-025\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Fatal\ Fury\ Special\ _\ Garou\ Densetsu\ Special\ \(NGM\-058\ _\ NGH\-058_\ set\ 2\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Fatal\ Fury\ Special\ _\ Garou\ Densetsu\ Special\ \(NGM\-058\ _\ NGH\-058_\ set\ 1\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Fatal\ Fury\ \-\ King\ of\ Fighters\ _\ Garou\ Densetsu\ \-\ Shukumei\ no\ Tatakai\ \(NGM\-033\ _\ NGH\-033\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Fatal\ Fury\ 2\ _\ Garou\ Densetsu\ 2\ \-\ Arata\-naru\ Tatakai\ \(NGM\-047\ _\ NGH\-047\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Fatal\ Fury\ 3\ \-\ Road\ to\ the\ Final\ Victory\ _\ Garou\ Densetsu\ 3\ \-\ Haruka\-naru\ Tatakai\ \(NGM\-069\ _\ NGH\-069\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Football\ Frenzy\ \(NGM\-034\ _\ NGH\-034\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Fight\ Fever\ \(set\ 2\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Fight\ Fever\ \(set\ 1\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Battle\ Flip\ Shot.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Fighters\ Swords\ \(Korean\ release\ of\ Samurai\ Shodown\ III\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Galaxy\ Fight\ \-\ Universal\ Warriors.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Ganryu\ _\ Musashi\ Ganryuki.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Garou\ \-\ Mark\ of\ the\ Wolves\ \(bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Garou\ \-\ Mark\ of\ the\ Wolves\ \(NGM\-2530\ _\ NGH\-2530\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Garou\ \-\ Mark\ of\ the\ Wolves\ \(prototype\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Garou\ \-\ Mark\ of\ the\ Wolves\ \(NGM\-2530\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Ghostlop\ \(prototype\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Goal\!\ Goal\!\ Goal\!.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Voltage\ Fighter\ \-\ Gowcaizer\ _\ Choujin\ Gakuen\ Gowcaizer.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Ghost\ Pilots\ \(NGH\-020_\ US\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Ghost\ Pilots\ \(NGM\-020\ _\ NGH\-020\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Gururin.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Choutetsu\ Brikin\'ger\ \-\ Iron\ Clad\ \(prototype_\ bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Choutetsu\ Brikin\'ger\ \-\ Iron\ Clad\ \(prototype\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ Irritating\ Maze\ _\ Ultra\ Denryu\ Iraira\ Bou.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Janshin\ Densetsu\ \-\ Quest\ of\ Jongmaster.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Jockey\ Grand\ Prix\ \(set\ 2\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Jockey\ Grand\ Prix\ \(set\ 1\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Puzzled\ _\ Joy\ Joy\ Kid\ \(NGM\-021\ _\ NGH\-021\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Far\ East\ of\ Eden\ \-\ Kabuki\ Klash\ _\ Tengai\ Makyou\ \-\ Shin\ Den.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Karnov\'s\ Revenge\ _\ Fighter\'s\ History\ Dynamite.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 10th\ Anniversary\ Extra\ Plus\ \(The\ King\ of\ Fighters\ 2002\ bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2002\ Magic\ Plus\ II\ \(bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2002\ Magic\ Plus\ \(bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2002\ Plus\ \(bootleg\ set\ 2\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2002\ Plus\ \(bootleg\ set\ 1\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2003\ \(bootleg\ set\ 2\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2003\ \(bootleg\ set\ 1\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2004\ Plus\ _\ Hero\ \(The\ King\ of\ Fighters\ 2003\ bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2004\ Ultra\ Plus\ \(The\ King\ of\ Fighters\ 2003\ bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 10th\ Anniversary\ 2005\ Unique\ \(The\ King\ of\ Fighters\ 2002\ bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Kizuna\ Encounter\ \-\ Super\ Tag\ Battle\ _\ Fu\'un\ Super\ Tag\ Battle.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 10th\ Anniversary\ \(The\ King\ of\ Fighters\ 2002\ bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2000\ \(not\ encrypted\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2000\ \(NGM\-2570\ _\ NGH\-2570\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2001\ \(NGH\-2621\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2001\ \(NGM\-262_\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2002\ \(bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2002\ \(NGM\-2650\ _\ NGH\-2650\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2003\ \(NGH\-2710\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ 2003\ \(NGM\-2710\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ Special\ Edition\ 2004\ \(The\ King\ of\ Fighters\ 2002\ bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'94\ \(NGM\-055\ _\ NGH\-055\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'95\ \(NGM\-084_\ alt\ board\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'95\ \(NGH\-084\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'95\ \(NGM\-084\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'96\ \(NGH\-214\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'96\ \(NGM\-214\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'97\ \(NGH\-2320\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'97\ \(Korean\ release\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'97\ Chongchu\ Jianghu\ Plus\ 2003\ \(bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'97\ Plus\ \(bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'97\ \(NGM\-2320\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'98\ \-\ The\ Slugfest\ _\ King\ of\ Fighters\ \'98\ \-\ Dream\ Match\ Never\ Ends\ \(NGM\-2420_\ alt\ board\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'98\ \-\ The\ Slugfest\ _\ King\ of\ Fighters\ \'98\ \-\ Dream\ Match\ Never\ Ends\ \(NGH\-2420\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'98\ \-\ The\ Slugfest\ _\ King\ of\ Fighters\ \'98\ \-\ Dream\ Match\ Never\ Ends\ \(Korean\ board\ 2\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'98\ \-\ The\ Slugfest\ _\ King\ of\ Fighters\ \'98\ \-\ Dream\ Match\ Never\ Ends\ \(Korean\ board\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'98\ \-\ The\ Slugfest\ _\ King\ of\ Fighters\ \'98\ \-\ Dream\ Match\ Never\ Ends\ \(NGM\-2420\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'99\ \-\ Millennium\ Battle\ \(earlier\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'99\ \-\ Millennium\ Battle\ \(NGH\-2510\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'99\ \-\ Millennium\ Battle\ \(Korean\ release\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'99\ \-\ Millennium\ Battle\ \(prototype\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ King\ of\ Fighters\ \'99\ \-\ Millennium\ Battle\ \(NGM\-2510\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/King\ of\ Gladiator\ \(The\ King\ of\ Fighters\ \'97\ bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/King\ of\ the\ Monsters\ 2\ \-\ The\ Next\ Thing\ \(prototype\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/King\ of\ the\ Monsters\ 2\ \-\ The\ Next\ Thing\ \(NGM\-039\ _\ NGH\-039\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/King\ of\ the\ Monsters\ \(set\ 2\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/King\ of\ the\ Monsters\ \(set\ 1\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Lansquenet\ 2004\ \(Shock\ Troopers\ \-\ 2nd\ Squad\ bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ Last\ Blade\ _\ Bakumatsu\ Roman\ \-\ Gekka\ no\ Kenshi\ \(NGH\-2340\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ Last\ Blade\ _\ Bakumatsu\ Roman\ \-\ Gekka\ no\ Kenshi\ \(NGM\-2340\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ Last\ Blade\ 2\ _\ Bakumatsu\ Roman\ \-\ Dai\ Ni\ Maku\ Gekka\ no\ Kenshi\ \(NGM\-2430\ _\ NGH\-2430\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ Last\ Soldier\ \(Korean\ release\ of\ The\ Last\ Blade\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/League\ Bowling\ \(NGM\-019\ _\ NGH\-019\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Legend\ of\ Success\ Joe\ _\ Ashita\ no\ Joe\ Densetsu.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Last\ Resort\ \(prototype\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Last\ Resort.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Magical\ Drop\ II.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Magical\ Drop\ III.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Magician\ Lord\ \(NGH\-005\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Magician\ Lord\ \(NGM\-005\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Mahjong\ Kyo\ Retsuden\ \(NGM\-004\ _\ NGH\-004\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Chibi\ Marukochan\ Deluxe\ Quiz.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Matrimelee\ _\ Shin\ Gouketsuji\ Ichizoku\ Toukon\ \(bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Matrimelee\ _\ Shin\ Gouketsuji\ Ichizoku\ Toukon\ \(NGM\-2660\ _\ NGH\-2660\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Money\ Puzzle\ Exchanger\ _\ Money\ Idol\ Exchanger.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Minasan\ no\ Okagesamadesu\!\ Dai\ Sugoroku\ Taikai\ \(MOM\-001\ _\ MOH\-001\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Metal\ Slug\ 4\ Plus\ \(bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Metal\ Slug\ 5\ Plus\ \(bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Metal\ Slug\ 2\ \-\ Super\ Vehicle\-001_II\ \(NGM\-2410\ _\ NGH\-2410\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Metal\ Slug\ 6\ \(Metal\ Slug\ 3\ bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Metal\ Slug\ 3\ \(NGH\-2560\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Metal\ Slug\ 3\ \(NGM\-2560\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Metal\ Slug\ 4\ \(NGH\-2630\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Metal\ Slug\ 4\ \(NGM\-2630\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Metal\ Slug\ 5\ \(NGH\-2680\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Metal\ Slug\ 5\ \(NGM\-2680\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Metal\ Slug\ X\ \-\ Super\ Vehicle\-001\ \(NGM\-2500\ _\ NGH\-2500\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Metal\ Slug\ \-\ Super\ Vehicle\-001.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Mutation\ Nation\ \(NGM\-014\ _\ NGH\-014\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/NAM\-1975\ \(NGM\-001\ _\ NGH\-001\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Ninja\ Combat\ \(NGH\-009\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Ninja\ Combat\ \(NGM\-009\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Ninja\ Commando.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Neo\ Bomberman.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Neo\-Geo\ Cup\ \'98\ \-\ The\ Road\ to\ the\ Victory.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Neo\ Drift\ Out\ \-\ New\ Technology.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Neo\ Mr.\ Do\!.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Ninja\ Master\'s\ \-\ Haoh\-ninpo\-cho.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Nightmare\ in\ the\ Dark\ \(bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Nightmare\ in\ the\ Dark.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Over\ Top.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Panic\ Bomber.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Puzzle\ Bobble\ 2\ _\ Bust\-A\-Move\ Again\ \(Neo\-Geo\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Puzzle\ Bobble\ _\ Bust\-A\-Move\ \(Neo\-Geo_\ bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Puzzle\ Bobble\ _\ Bust\-A\-Move\ \(Neo\-Geo_\ NGM\-083\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Pleasure\ Goal\ _\ Futsal\ \-\ 5\ on\ 5\ Mini\ Soccer\ \(NGM\-219\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Pochi\ and\ Nyaa.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Pop\ \'n\ Bounce\ _\ Gapporin.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Prehistoric\ Isle\ 2.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Power\ Spikes\ II\ \(NGM\-068\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Pulstar.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Puzzle\ De\ Pon\!\ R\!.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Puzzle\ De\ Pon\!.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Quiz\ Meitantei\ Neo\ _\ Geo\ \-\ Quiz\ Daisousa\ Sen\ part\ 2\ \(NGM\-042\ _\ NGH\-042\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Quiz\ Daisousa\ Sen\ \-\ The\ Last\ Count\ Down\ \(Korean\ release\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Quiz\ Daisousa\ Sen\ \-\ The\ Last\ Count\ Down\ \(NGM\-023\ _\ NGH\-023\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Quiz\ King\ of\ Fighters\ \(Korean\ release\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Quiz\ King\ of\ Fighters\ \(SAM\-080\ _\ SAH\-080\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Ragnagard\ _\ Shin\-Oh\-Ken.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Real\ Bout\ Fatal\ Fury\ _\ Real\ Bout\ Garou\ Densetsu\ \(bug\ fix\ revision\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Real\ Bout\ Fatal\ Fury\ _\ Real\ Bout\ Garou\ Densetsu\ \(NGM\-095\ _\ NGH\-095\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Real\ Bout\ Fatal\ Fury\ 2\ \-\ The\ Newcomers\ _\ Real\ Bout\ Garou\ Densetsu\ 2\ \-\ The\ Newcomers\ \(NGH\-2400\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Real\ Bout\ Fatal\ Fury\ 2\ \-\ The\ Newcomers\ \(Korean\ release\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Real\ Bout\ Fatal\ Fury\ 2\ \-\ The\ Newcomers\ _\ Real\ Bout\ Garou\ Densetsu\ 2\ \-\ The\ Newcomers\ \(NGM\-2400\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Real\ Bout\ Fatal\ Fury\ Special\ _\ Real\ Bout\ Garou\ Densetsu\ Special\ \(Korean\ release\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Real\ Bout\ Fatal\ Fury\ Special\ _\ Real\ Bout\ Garou\ Densetsu\ Special.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Riding\ Hero\ \(set\ 2\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Riding\ Hero\ \(NGM\-006\ _\ NGH\-006\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Robo\ Army.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Rage\ of\ the\ Dragons\ \(NGM\-2640_\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Strikers\ 1945\ Plus.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Samurai\ Shodown\ V\ Special\ _\ Samurai\ Spirits\ Zero\ Special\ \(NGH\-2720_\ 1st\ release_\ censored\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Samurai\ Shodown\ V\ Special\ _\ Samurai\ Spirits\ Zero\ Special\ \(NGH\-2720_\ 2nd\ release_\ less\ censored\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Samurai\ Shodown\ V\ Special\ _\ Samurai\ Spirits\ Zero\ Special\ \(NGM\-2720\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Saulabi\ Spirits\ _\ Jin\ Saulabi\ Tu\ Hon\ \(Korean\ release\ of\ Samurai\ Shodown\ II\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Samurai\ Shodown\ II\ _\ Shin\ Samurai\ Spirits\ \-\ Haohmaru\ Jigokuhen\ \(NGM\-063\ _\ NGH\-063\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Samurai\ Shodown\ III\ _\ Samurai\ Spirits\ \-\ Zankurou\ Musouken\ \(NGH\-087\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Samurai\ Shodown\ III\ _\ Samurai\ Spirits\ \-\ Zankurou\ Musouken\ \(NGM\-087\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Pae\ Wang\ Jeon\ Seol\ _\ Legend\ of\ a\ Warrior\ \(Korean\ censored\ Samurai\ Shodown\ IV\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Samurai\ Shodown\ IV\ \-\ Amakusa\'s\ Revenge\ _\ Samurai\ Spirits\ \-\ Amakusa\ Kourin\ \(NGM\-222\ _\ NGH\-222\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Samurai\ Shodown\ V\ _\ Samurai\ Spirits\ Zero\ \(bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Samurai\ Shodown\ V\ _\ Samurai\ Spirits\ Zero\ \(NGH\-2700\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Samurai\ Shodown\ V\ _\ Samurai\ Spirits\ Zero\ \(NGM\-2700\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Samurai\ Shodown\ _\ Samurai\ Spirits\ \(NGH\-045\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Samurai\ Shodown\ _\ Samurai\ Spirits\ \(NGM\-045\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Savage\ Reign\ _\ Fu\'un\ Mokushiroku\ \-\ Kakutou\ Sousei.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Super\ Dodge\ Ball\ _\ Kunio\ no\ Nekketsu\ Toukyuu\ Densetsu.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Sengoku\ 2\ _\ Sengoku\ Denshou\ 2.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Sengoku\ 3\ _\ Sengoku\ Densho\ 2001.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Sengoku\ _\ Sengoku\ Denshou\ \(NGH\-017_\ US\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Sengoku\ _\ Sengoku\ Denshou\ \(NGM\-017\ _\ NGH\-017\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Shock\ Troopers\ \-\ 2nd\ Squad.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Shock\ Troopers\ \(set\ 2\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Shock\ Troopers\ \(set\ 1\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Soccer\ Brawl\ \(NGH\-031\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Soccer\ Brawl\ \(NGM\-031\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Aero\ Fighters\ 2\ _\ Sonic\ Wings\ 2.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Aero\ Fighters\ 3\ _\ Sonic\ Wings\ 3.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Spin\ Master\ _\ Miracle\ Adventure.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Super\ Sidekicks\ 2\ \-\ The\ World\ Championship\ _\ Tokuten\ Ou\ 2\ \-\ Real\ Fight\ Football\ \(NGM\-061\ _\ NGH\-061\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Super\ Sidekicks\ 3\ \-\ The\ Next\ Glory\ _\ Tokuten\ Ou\ 3\ \-\ Eikou\ e\ no\ Michi.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ Ultimate\ 11\ \-\ The\ SNK\ Football\ Championship\ _\ Tokuten\ Ou\ \-\ Honoo\ no\ Libero.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Super\ Sidekicks\ _\ Tokuten\ Ou.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Stakes\ Winner\ 2.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Stakes\ Winner\ _\ Stakes\ Winner\ \-\ GI\ Kinzen\ \ Seiha\ e\ no\ Michi.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Street\ Hoop\ _\ Street\ Slam\ _\ Dunk\ Dream\ \(DEM\-004\ _\ DEH\-004\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/The\ Super\ Spy\ \(NGM\-011\ _\ NGH\-011\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/SNK\ vs.\ Capcom\ \-\ SVC\ Chaos\ \(bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/SNK\ vs.\ Capcom\ \-\ SVC\ Chaos\ Plus\ \(bootleg\ set\ 2\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/SNK\ vs.\ Capcom\ \-\ SVC\ Chaos\ Plus\ \(bootleg\ set\ 1\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/SNK\ vs.\ Capcom\ \-\ SVC\ Chaos\ Super\ Plus\ \(bootleg\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/SNK\ vs.\ Capcom\ \-\ SVC\ Chaos\ \(NGM\-2690\ _\ NGH\-2690\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Top\ Hunter\ \-\ Roddy\ _\ Cathy\ \(NGH\-046\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Top\ Hunter\ \-\ Roddy\ _\ Cathy\ \(NGM\-046\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Top\ Player\'s\ Golf\ \(NGM\-003\ _\ NGH\-003\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Thrash\ Rally\ \(ALM\-003\ _\ ALH\-003\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Neo\ Turf\ Masters\ _\ Big\ Tournament\ Golf.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Twinkle\ Star\ Sprites.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Tecmo\ World\ Soccer\ \'96.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Viewpoint.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/V\-Liner\ \(set\ 2\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/V\-Liner\ \(set\ 1\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Waku\ Waku\ 7.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/World\ Heroes\ \(set\ 3\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/World\ Heroes\ \(ALH\-005\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/World\ Heroes\ \(ALM\-005\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/World\ Heroes\ 2\ Jet\ \(ADM\-007\ _\ ADH\-007\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/World\ Heroes\ 2\ \(ALM\-006\ _\ ALH\-006\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/World\ Heroes\ Perfect.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Windjammers\ _\ Flying\ Power\ Disc.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Zed\ Blade\ _\ Operation\ Ragnarok.png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Zintrick\ _\ Oshidashi\ Zentrix\ \(bootleg\ of\ CD\ version\).png .
ln /mnt/space/Games/libretro-thumbnails/FB\ Alpha\ \-\ Arcade\ Games/Named_Boxarts/Zupapa\!.png .
